### ISSUE TITLE
Socket IO Server Enhancer should ignore msgs where from and to are the same?

### ISSUE THREAD

**Issue by ghost** [ben-ng/gaggle#13]
https://github.com/ben-ng/gaggle/blob/master/lib/socket-io-server-enhancer.js

On msg, should it not check if dat.from == dat.to and return if that is true? Is there a case where from and to can be the same, but a broadcast would have to happen?

**Comment by ben-ng** [comment]
I'm pretty sure that a server shouldn't ignore a message to itself. Otherwise, the Raft algorithm wouldn't work, because each server has to vote for itself during leader election. You can try changing the code, and checking to see if the tests still pass.

**Comment by ghost** [comment]
The nodes are independent of the server (not sure what you mean by a server ignoring a messagges to itself) and I did make the change for the server part and things are fine (less repetition is what I am aiming for). Heartbeat messages (numerous) that have same sender/receiver should not be broadcasted.
