### ISSUE TITLE
Does gaggle rely on a central server?

### ISSUE THREAD

**Issue by jeorgen** [ben-ng/gaggle#9]
Hi, reading through your examples, it seems like gaggle relies on either a central Redis or Socket.io server. Wouldn't this create a single point of failure, or have I misunderstood something?

**Comment by ben-ng** [comment]
Well you can run a Redis or Socket.io cluster, but that's besides the point; you can implement channels that hardcode the IP addresses of each node so it really is point-to-point. The reason why I started with Redis and Socket is because they were easier to build demos with.

**Comment by ben-ng** [comment]
Closing in favor of #11

**Comment by bagrounds** [comment]
I demonstrate in a simple demo [here](https://gitlab.com/bagrounds/gaggle-demo) that you don't need a central socket.io server.

The demo is built for multiple processes on a single machine, but this could be extended to multiple machines with the addition of some service discovery mechanism.

The way it works is that, periodically, each node will attempt to start a socket.io server (on the same port on localhost) if that node is a candidate.

I've played with this, and it works pretty well. Any node might be hosting the server at any time, and the cluster will quickly recover if the node hosting the server fails.

This could be made easier to accomplish if there were an "I'm a candidate" event exposed by the gaggle event emitter.

**Comment by ben-ng** [comment]
@bagrounds this is impressive work! I've never been too happy with gaggle's API. It's very boilerplatey, and difficult to extend to new situations, such as this. I'd be be happy to merge an improvement.
